changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
  categories:
    - title: "💥 Breaking Change 💥"
      labels:
        - Semver-Major
        - breaking-change
    - title: "🎉 Enhancements & New Features 🎉"
      labels:
        - Semver-Minor
        - enhancement
        - feature
    - title: "🐛 Bug Fixes 🐛"
      labels:
        - fix
        - bugfix
        - bug
    - title: "🔧 Maintenance 🔧"
      labels:
        - chore
        - github_actions
    - title: Other Changes
      labels:
        - "*"
