name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: What country are you in?
    validations:
      required: true
  - type: input
    id: resmed-myair-version
    attributes:
      label: resmed_myair Version
    validations:
      required: true
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant logs. This will be automatically formatted into code, so no need for backticks. [How to enable debug logging.](https://www.home-assistant.io/components/logger/)
      render: shell
  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Anything else we need to know?
