name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Debug Variables
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.workspace: ${{ github.workspace }}"          
          echo "github.event.repository.default_branch: ${{ github.event.repository.default_branch }}"
          echo "github.event.release.target_commitish: ${{ github.event.release.target_commitish }}"
          echo "github.event.release.prerelease: ${{ github.event.release.prerelease }}"
          echo "github.event.release.draft: ${{ github.event.release.draft }}"

      - name: "Set version number"
        run: |
            sed -i 's/\"version\"\s*\:\s*\".*\"/\"version\"\:\"${{ github.ref_name }}\"/g' ${{ github.workspace }}/custom_components/resmed_myair/manifest.json
            sed -i 's/VERSION\s*\=\s*\".*\"/VERSION \= \"${{ github.ref_name }}\"/' ${{ github.workspace }}/custom_components/resmed_myair/const.py          
      # Pack the resmed_myair dir as a zip and upload to the release
      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/resmed_myair
          zip resmed_myair.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@2.10.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/resmed_myair/resmed_myair.zip
          asset_name: resmed_myair.zip
          tag: ${{ github.ref }}
          overwrite: true
